use QL_BANHANG
go
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(1, 'Nike React Infinity Run Flyknit', 'NIKE', 'MEN', '1', 160)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(2, 'Nike React Miler', 'NIKE', 'MEN', '1', 130)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(3, 'Nike Air Zoom Pegasus 37', 'NIKE', 'WOMEN', '1', 120)   

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(4, 'Nike Joyride Run Flyknit', 'NIKE', 'WOMEN', '1', 180)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(5, 'Nike Mercurial Vapor 13 Elite FG', 'NIKE', 'WOMEN', '2', 250)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(6, 'Nike Phantom Vision Elite Dynamic Fit FG', 'NIKE', 'WOMEN', '2', 150)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(7, 'Nike Phantom Venom Academy FG', 'NIKE', 'WOMEN', '2', 80)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(8, 'Nike Mercurial Vapor 13 Elite Tech Craft FG', 'NIKE', 'MEN', '2', 145)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(9, 'Nike Mercurial Superfly 7 Pro MDS FG', 'NIKE', 'MEN', '2', 137)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(10, 'Nike Air Force 1', 'NIKE', 'KIDS', '2', 90)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(11, 'Nike Air Max 90', 'NIKE', 'KIDS', '2', 100)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(12, 'Nike Air Max 90 LTR', 'NIKE', 'KIDS', '2', 110)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(13, 'Nike Joyride Dual Run', 'NIKE', 'KIDS', '1', 110)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(14, 'Nike Renew Run', 'NIKE', 'KIDS', '1', 80)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(16, 'Bridgport Advice', 'HUSHPUPPIES', 'MEN', '2', 30)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(15, 'Beck', 'HUSHPUPPIES', 'MEN', '2', 80)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(17, 'Fester', 'HUSHPUPPIES', 'MEN', '2', 70)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(18, 'Pixel', 'HUSHPUPPIES', 'MEN', '2', 75)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(19, 'Austin', 'HUSHPUPPIES', 'MEN', '2',  75)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(20, 'SS-HL-0135', 'HUSHPUPPIES', 'WOMEN', '2', 30)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(21, 'SS-HL-0136', 'HUSHPUPPIES', 'WOMEN', '2',  50)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(22, 'SS-HL-0128', 'HUSHPUPPIES', 'WOMEN', '2', 35)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(23, 'SS-MS-0075', 'HUSHPUPPIES', 'WOMEN', '2', 25)
    
INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(24, 'SS-MS-0075', 'HUSHPUPPIES', 'WOMEN', '2', 35)

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(25, 'SS-PM-0093', 'HUSHPUPPIES', 'WOMEN', '2', 30)

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(26, 'Nizza X Disney', 'ADIDAS', 'KIDS', '2', 55)

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(27, 'X_PLR', 'ADIDAS', 'KIDS', '2', 65)

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(28, 'Stan Smith', 'ADIDAS', 'KIDS', '2', 55)

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(29, 'NMD_R1', 'ADIDAS', 'KIDS', '1',  120)

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(30, 'NMD_R1 Flash Red', 'ADIDAS', 'WOMEN',  '2', 140)

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(31, 'Superstar', 'ADIDAS', 'WOMEN', '2',  90)

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(32, 'Club C Revenge Mens', 'Reebok', 'MEN', '2', 70)

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(33, 'SK80-Low', 'Vans', 'MEN', '2', 60)    

INSERT INTO PRODUCT(ID, PNAME, BRAND, GENDER, CATE_ID, PRICE) VALUES(34, 'Michael Feburary SK8-Hi', 'Vans', 'MEN', '2', 72)