use QL_BANHANG
go

INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES('1', 'RUNNING')
INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES('2', 'FOOTBALL')
INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES('3', 'CASUAL')
INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES('4', 'FORMAL')
